version: '3'

services:
#  db:
#    image: "postgres:14.8"
#    volumes:
#      - ./docker/data/postgres_data:/var/lib/postgresql/data
#      - ./docker/create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
#    restart: always
#    environment:
#      - POSTGRES_PASSWORD=mes
#    ports:
#      - "5432:5432"
#    expose:
#      - 5432
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./testjoeflow:/project
    environment:
      - PYTHONUNBUFFERED=0
      - DJANGO_SETTINGS_MODULE=testjoeflow.settings
    working_dir: "/project"
    ports:
      - "8000:8000"
#    depends_on:
#      - db

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./docker/data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    restart: always

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A mes worker -B
    volumes:
      - ./mes:/project
    depends_on:
      - web
      - rabbitmq

  flower:
   image: mher/flower
   container_name: flower
   command: celery flower
   environment:
     - CELERY_BROKER_URL=amqp://rmuser:rmpassword@rabbitmq:5672
     - FLOWER_PORT=8888
   ports:
   - 8888:8888
   volumes:
   - ./docker/data/flower_data:/data

#  openldap:
#    image: osixia/openldap:1.5.0
#    container_name: openldap
#    volumes:
#      - ./docker/data/ldap_db:/var/lib/ldap
#      - ./docker/ldap_config:/etc/ldap/slapd.d
#    environment:
#      - LDAP_ORGANISATION=hightechplatnt-ru
#      - LDAP_DOMAIN=hightechplatnt.ru
#      - LDAP_ADMIN_PASSWORD=admin
#      - LDAP_CONFIG_PASSWORD=config
#      - LDAP_RFC2307BIS_SCHEMA=true
#      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
#      - LDAP_TLS_VERIFY_CLIENT=never
#    ports:
#      - "389:389"
#
#  openldap-ui:
#    image: wheelybird/ldap-user-manager:v1.5
#    container_name: openldap-ui
#    environment:
#      - LDAP_URI=ldap://openldap
#      - LDAP_BASE_DN=dc=hightechplatnt,dc=ru
#      - LDAP_REQUIRE_STARTTLS=FALSE
#      - LDAP_ADMINS_GROUP=admins
#      - LDAP_ADMIN_BIND_DN=cn=admin,dc=hightechplatnt,dc=ru
#      - LDAP_ADMIN_BIND_PWD=admin
#      - LDAP_IGNORE_CERT_ERRORS=true
#      - FORCE_RFC2307BIS=TRUE
#      - NO_HTTPS=TRUE
#      - PASSWORD_HASH=SSHA
#      - SERVER_HOSTNAME=localhost:18080
#    depends_on:
#      - openldap
#    ports:
#      - 18080:80
